# Soal ML 
## prediksi diagnosa Diabetes dengan Machine Learning supervised learning
Untuk memprediksi diagnosis diabetes menggunakan Supervised Learning, kita biasanya menggunakan data klinis pasien (seperti kadar gula darah, tekanan darah, usia, dan indeks massa tubuh) untuk melatih model agar bisa mengklasifikasikan apakah seorang pasien Positif Diabetes (1) atau Negatif Diabetes (0).

## 1. Alur Kerja (Workflow) Data
Sebelum masuk ke kode, berikut adalah bagaimana data diproses di dalam sistem:

1. Fitur (X): Variabel medis pasien (Gula Darah, BMI, Tekanan Darah, Umur).

2. Label (y): Target diagnosis (0 = Sehat, 1 = Diabetes).

3. Pipeline: Mengisi data kosong (jika ada), menyamakan skala angka, lalu mengklasifikasikannya.

## Data collection dan EDA (Exploratory Data Analysis)

In [3]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

# =====================================================================
# 1. MEMBUAT DATASET MEDIS SIMULASI (Data Historis Pasien)
# =====================================================================
# Fitur: [Glukosa, TekananDarah, BMI, Umur]
data_pasien = {
    'Glukosa': [85, 168, 89, 137, 116, 78, 115, 197, 125, 140],
    'TekananDarah': [66, 74, 60, 40, 74, 50, 0, 70, 96, 85], # Angka 0 di tekanan darah dianggap data korup/hilang
    'BMI': [26.6, 31.0, 28.1, 43.1, 25.6, 31.0, 35.3, 30.5, 0.0, 37.4],
    'Umur': [31, 54, 21, 33, 30, 26, 29, 53, 54, 41],
    'Diabetes': [0, 1, 0, 1, 0, 0, 0, 1, 1, 1] # 0 = Negatif, 1 = Positif
}

df = pd.DataFrame(data_pasien)
display(df)

   Glukosa  TekananDarah   BMI  Umur  Diabetes
0       85            66  26.6    31         0
1      168            74  31.0    54         1
2       89            60  28.1    21         0
3      137            40  43.1    33         1
4      116            74  25.6    30         0
5       78            50  31.0    26         0
6      115             0  35.3    29         0
7      197            70  30.5    53         1
8      125            96   0.0    54         1
9      140            85  37.4    41         1

In [5]:
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import pandas as pd

# Create age groups
age_bins = [0, 25, 40, 60, 100] # Define age bin edges
age_labels = ['<25', '25-40', '40-60', '>60'] # Labels for age bins
X_with_age_group = df.copy()
X_with_age_group['Kelompok Usia'] = pd.cut(X_with_age_group['Umur'], bins=age_bins, labels=age_labels, right=False)

# Features to plot (excluding 'Umur' itself, as it's used for grouping)
features_to_plot = ['Glukosa', 'TekananDarah', 'BMI']

display(X_with_age_group)
num_features_to_plot = len(features_to_plot)

# Determine the number of rows and columns for subplots
rows = (num_features_to_plot + 1) // 2
cols = 2 if num_features_to_plot > 1 else 1

   Glukosa  TekananDarah   BMI  Umur  Diabetes Kelompok Usia
0       85            66  26.6    31         0         25-40
1      168            74  31.0    54         1         40-60
2       89            60  28.1    21         0           <25
3      137            40  43.1    33         1         25-40
4      116            74  25.6    30         0         25-40
5       78            50  31.0    26         0         25-40
6      115             0  35.3    29         0         25-40
7      197            70  30.5    53         1         40-60
8      125            96   0.0    54         1         40-60
9      140            85  37.4    41         1         40-60

## Buatlah visualisasi data dengan plotly "Distribusi Fitur Menggunakan Subplot Plotly"

<img width="774" height="625" alt="ML" src="plot.png" />

## 2. MEMBUAT PIPELINE SUPERVISED LEARNING

## 3. PROSES PELATIHAN (TRAINING)

## 4. EVALUASI MODEL


## 5. IMPLEMENTASI: PREDIKSI PASIEN BARU DI KLINIK

Datang pasien baru dengan data medis sebagai berikut:
Glukosa: 160, Tekanan Darah: 80, BMI: 34.2, Umur: 45